version: '3.8'

services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apache_server
    restart: always
    ports:
      - "8050:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysql
    networks:
      - network_server

  mysql:
    image: mysql:8.0
    hostname: mysql_docker
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projeto
      MYSQL_USER: aluno
      MYSQL_PASSWORD: 123456
    ports:
      - "3356:3356"
    command: --port=3356
    volumes:
      - /mysql_data:/var/lib/mysql
    networks:
      - network_server

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_server
    restart: always
    ports:
      - "8051:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3356
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - network_server

networks:
  network_server:

